### ISSUE TITLE
How do I add these processors to my nifi setup?

### ISSUE THREAD

**Issue by GaryGav** [wasperen/nifi-couchdb#2]
Hi, 

These processors would be very helpful for me and I would love to add them to my nifi setup however I am unsure how to go about it. Is there a guide somewhere I could read for dummies lol I have tried googling but haven't been able to find anything helpful.

Thanks in advance.

**Comment by GaryGav** [comment]
I managed to find out a bit more information on installing the processors but I am stuck on the error 

"[ERROR] Failed to execute goal on project nifi-couchdb-processors: Could not resolve dependencies for project org.asperen:nifi-couchdb-processors:jar:1.0-SNAPSHOT: Could not find artifact org.lightcouch:lightcouch:jar:0.2.1-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots)"

Can anyone explain what I am doing wrong? Below is the full install messages.

C:\Demo\nifi-couchdb-master>mvn clean install -U
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 3 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 3 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] nifi-couchdb-bundle                                                [pom]
[INFO] nifi-couchdb-processors                                            [jar]
[INFO] nifi-couchdb-nar                                                   [nar]
[INFO]
[INFO] ------------------< org.asperen:nifi-couchdb-bundle >-------------------
[INFO] Building nifi-couchdb-bundle 1.0-SNAPSHOT                          [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ nifi-couchdb-bundle ---
[INFO] Deleting C:\Demo\nifi-couchdb-master\target
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven) @ nifi-couchdb-bundle ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ nifi-couchdb-bundle ---
[INFO]
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ nifi-couchdb-bundle ---
[INFO]
[INFO] --- maven-compiler-plugin:3.2:testCompile (groovy-tests) @ nifi-couchdb-bundle ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-site-plugin:3.4:attach-descriptor (attach-descriptor) @ nifi-couchdb-bundle ---
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ nifi-couchdb-bundle ---
[INFO] Installing C:\Demo\nifi-couchdb-master\pom.xml to C:\Users\Gary.Gavigan\.m2\repository\org\asperen\nifi-couchdb-bundle\1.0-SNAPSHOT\nifi-couchdb-bundle-1.0-SNAPSHOT.pom
[INFO]
[INFO] ----------------< org.asperen:nifi-couchdb-processors >-----------------
[INFO] Building nifi-couchdb-processors 1.0-SNAPSHOT                      [2/3]
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from apache.snapshots: http://repository.apache.org/snapshots/org/lightcouch/lightcouch/0.2.1-SNAPSHOT/maven-metadata.xml
Downloading from apache.snapshots: http://repository.apache.org/snapshots/org/lightcouch/lightcouch/0.2.1-SNAPSHOT/lightcouch-0.2.1-SNAPSHOT.pom
[WARNING] The POM for org.lightcouch:lightcouch:jar:0.2.1-SNAPSHOT is missing, no dependency information available
Downloading from apache.snapshots: http://repository.apache.org/snapshots/org/lightcouch/lightcouch/0.2.1-SNAPSHOT/lightcouch-0.2.1-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for nifi-couchdb-bundle 1.0-SNAPSHOT:
[INFO]
[INFO] nifi-couchdb-bundle ................................ SUCCESS [  1.052 s]
[INFO] nifi-couchdb-processors ............................ FAILURE [  0.984 s]
[INFO] nifi-couchdb-nar ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.386 s
[INFO] Finished at: 2018-12-12T10:18:21Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project nifi-couchdb-processors: Could not resolve dependencies for project org.asperen:nifi-couchdb-processors:jar:1.0-SNAPSHOT: Could not find artifact org.lightcouch:lightcouch:jar:0.2.1-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :nifi-couchdb-processors

**Comment by wasperen** [comment]
HeyGreat to hear of your interest in this project!The code does rely on lightcouch. You will need to get the jar for that dependency and put it in the lib directory of nifi.WOn Dec 12, 2018 11:23 AM, GaryGav <notifications@github.com> wrote:I managed to find out a bit more information on installing the processors but I am stuck on the error
"[ERROR] Failed to execute goal on project nifi-couchdb-processors: Could not resolve dependencies for project org.asperen:nifi-couchdb-processors:jar:1.0-SNAPSHOT: Could not find artifact org.lightcouch:lightcouch:jar:0.2.1-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots)"
Can anyone explain what I am doing wrong? Below is the full install messages.
C:\Demo\nifi-couchdb-master>mvn clean install -U
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 3 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 3 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] nifi-couchdb-bundle                                                [pom]
[INFO] nifi-couchdb-processors                                            [jar]
[INFO] nifi-couchdb-nar                                                   [nar]
[INFO]
[INFO] ------------------< org.asperen:nifi-couchdb-bundle >-------------------
[INFO] Building nifi-couchdb-bundle 1.0-SNAPSHOT                          [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ nifi-couchdb-bundle ---
[INFO] Deleting C:\Demo\nifi-couchdb-master\target
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven) @ nifi-couchdb-bundle ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ nifi-couchdb-bundle ---
[INFO]
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ nifi-couchdb-bundle ---
[INFO]
[INFO] --- maven-compiler-plugin:3.2:testCompile (groovy-tests) @ nifi-couchdb-bundle ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-site-plugin:3.4:attach-descriptor (attach-descriptor) @ nifi-couchdb-bundle ---
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ nifi-couchdb-bundle ---
[INFO] Installing C:\Demo\nifi-couchdb-master\pom.xml to C:\Users\Gary.Gavigan.m2\repository\org\asperen\nifi-couchdb-bundle\1.0-SNAPSHOT\nifi-couchdb-bundle-1.0-SNAPSHOT.pom
[INFO]
[INFO] ----------------< org.asperen:nifi-couchdb-processors >-----------------
[INFO] Building nifi-couchdb-processors 1.0-SNAPSHOT                      [2/3]
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from apache.snapshots: http://repository.apache.org/snapshots/org/lightcouch/lightcouch/0.2.1-SNAPSHOT/maven-metadata.xml
Downloading from apache.snapshots: http://repository.apache.org/snapshots/org/lightcouch/lightcouch/0.2.1-SNAPSHOT/lightcouch-0.2.1-SNAPSHOT.pom
[WARNING] The POM for org.lightcouch:lightcouch:jar:0.2.1-SNAPSHOT is missing, no dependency information available
Downloading from apache.snapshots: http://repository.apache.org/snapshots/org/lightcouch/lightcouch/0.2.1-SNAPSHOT/lightcouch-0.2.1-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for nifi-couchdb-bundle 1.0-SNAPSHOT:
[INFO]
[INFO] nifi-couchdb-bundle ................................ SUCCESS [  1.052 s]
[INFO] nifi-couchdb-processors ............................ FAILURE [  0.984 s]
[INFO] nifi-couchdb-nar ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.386 s
[INFO] Finished at: 2018-12-12T10:18:21Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project nifi-couchdb-processors: Could not resolve dependencies for project org.asperen:nifi-couchdb-processors:jar:1.0-SNAPSHOT: Could not find artifact org.lightcouch:lightcouch:jar:0.2.1-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn  -rf :nifi-couchdb-processors

**Comment by GaryGav** [comment]
Hi Willem! 
Thank you for responding, and yes I am very interested in this project. Apologies for my lack of knowledge in all of this. 

I found this video on creating processors https://www.youtube.com/watch?v=3ldmNFlelhw which led me to think I could download your nifi-couchdb-master folder to my computer, direct maven (which I have also never used before) to that folder and it and type "mvn install" and it would create the NAR files for the processors which I would place in the nifi/lib folder. 

I have downloaded the lightcouch-0.2.0.jar from http://www.lightcouch.org/lightcouch-guide.html#dependencies. I have placed the the lightcouch-0.2.0.jar in both the nifi/lib folder and my maven/lib as I was not sure how maven would know where my nifi folder was but I still get the same error. 

"Could not resolve dependencies for project org.asperen:nifi-couchdb-processors:jar:1.0-SNAPSHOT: Could not find artifact org.lightcouch:lightcouch:jar:0.2.1-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots)."

Does the nifi-couchdb-master folder need to be within nifi directory for this to work? 

The error mentions 0.2.1-SNAPSHOT.jar but I cannot find this version of the lightcouch.jar from googling. 

![image](https://user-images.githubusercontent.com/39549757/49868040-1cb8d680-fe04-11e8-9448-2d4e4acf670b.png)

Apologies again for my lack of knowledge but any help you can provide would be greatly appreciated.

Cheers,

Gary

**Comment by wasperen** [comment]
Hey Gary --Let me have a look. I think there is an adaptation I did to lightcouch...WOn Dec 12, 2018 12:56 PM, GaryGav <notifications@github.com> wrote:Hi Willem!
Thank you for responding, and yes I am very interested in this project. Apologies for my lack of knowledge in all of this.
I found this video on creating processors https://www.youtube.com/watch?v=3ldmNFlelhw which led me to think I could download your nifi-couchdb-master folder to my computer, direct maven (which I have also never used before) to that folder and it and type "mvn install" and it would create the NAR files for the processors which I would place in the nifi/lib folder.
I have downloaded the lightcouch-0.2.0.jar from http://www.lightcouch.org/lightcouch-guide.html#dependencies. I have placed the the lightcouch-0.2.0.jar in both the nifi/lib folder and my maven/lib as I was not sure how maven would know where my nifi folder was but I still get the same error.
"Could not resolve dependencies for project org.asperen:nifi-couchdb-processors:jar:1.0-SNAPSHOT: Could not find artifact org.lightcouch:lightcouch:jar:0.2.1-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots)."
Does the nifi-couchdb-master folder need to be within nifi directory for this to work?
The error mentions 0.2.1-SNAPSHOT.jar but I cannot find this version of the lightcouch.jar from googling.

Apologies again for my lack of knowledge but any help you can provide would be greatly appreciated.
Cheers,
Gary

**Comment by wasperen** [comment]
Hey 

Have a look here: https://github.com/lightcouch/LightCouch/commit/d6eeedae21f32387f13484d9474b95e17cece09b

That is the commit I did and added a pull request for. Clone that project in a separate project and build it. That should create the 0.2.1 snapshot that this project relies on.

W

**Comment by GaryGav** [comment]
Hi,

Thanks for taking the time to try to help me with this, it is appreciated!

I tried to build it however and got errors about the source and target versions below;
![image](https://user-images.githubusercontent.com/39549757/49874367-36631980-fe16-11e8-8c87-052bc3cbdc56.png)

I changed the pom.xml from;

![image](https://user-images.githubusercontent.com/39549757/49874590-cb661280-fe16-11e8-8b04-6b7a4e8a6550.png)

to;

![image](https://user-images.githubusercontent.com/39549757/49874660-f05a8580-fe16-11e8-89fa-ea6ad5bac45d.png)

But now I am getting the error;

![image](https://user-images.githubusercontent.com/39549757/49874518-99ed4700-fe16-11e8-8011-329f0992aa5b.png)

I also tried changing source to "6" rather than "1.6" but had the same error.

Cheers,
Gary.

**Comment by GaryGav** [comment]
Managed to get a little bit further changing to 1.8 for source and target;

![image](https://user-images.githubusercontent.com/39549757/49876973-58f83100-fe1c-11e8-9179-0fb2dab66030.png)

**Comment by GaryGav** [comment]
I tried it again using command "mvn clean install -Dmaven.test.skip=true" to skip the tests as it was saying unauthorized. This created the JAR and the nifi-couchdb-nar seems to have generated so I will now try to get this in my nifi setup! 

![image](https://user-images.githubusercontent.com/39549757/49878104-bf7e4e80-fe1e-11e8-966b-14d0f76eb5af.png)

**Comment by GaryGav** [comment]
Haven't tried using them just yet but they're loaded into my NIFI setup!

![image](https://user-images.githubusercontent.com/39549757/49881606-b1ccc700-fe26-11e8-9791-8de98663d551.png)

Thank you for your help and patience!
